### ISSUE TITLE
invalid url response code status=461 

### ISSUE THREAD

**Issue by GitHub666k** [csfrancis/proxytv#1]
Hi,

When i start : 
```
 ./dist/proxytv -config TV.yaml
INFO[2024-11-15T21:59:49Z] starting proxytv                              config=TV.yaml gitCommit=8e7aad7
INFO[2024-11-15T21:59:49Z] loading IPTV m3u                              url="http://myurl.onl/get.php?username=REDACTED&password=REDACTED&output=ts&type=m3u_plus"
PANI[2024-11-15T21:59:49Z] invalid url response code                     status=461 uri="http://myurl.onl/get.php?username=********&password=*********&output=ts&type=m3u_plus"
panic: (*logrus.Entry) 0xc00027a070

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00027a000, 0x0, {0xc000256080, 0x19})
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x485
github.com/sirupsen/logrus.(*Entry).Log(0xc00027a000, 0x0, {0xc000037810?, 0x6?, 0x9ccae0?})
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/csfrancis/proxytv.loadReader({0xc0001d8000, 0x5d})
        /root/proxytv/provider.go:159 +0x59c
github.com/csfrancis/proxytv.(*Provider).Refresh(0xc0000f8360)
        /root/proxytv/provider.go:285 +0xd9
main.main()
        /root/proxytv/cmd/main.go:112 +0x4a5

```

I have : 
```
cat TV.yaml
logLevel: "debug" # Log level (optional, default: "info")
iptvUrl: "http://myrul.onl/get.php?username=********&password=********&output=ts&type=m3u_plus" # URL to the IPTV M3U file (required)
epgUrl: "http://example.com/xmltv.php?username=********&password=********" # URL to the EPG XML file (required)
listenAddress: ":6078" # Address to listen on (optional, default: ":6078")
serverAddress: "localhost:6078" # Base server address (required)
refreshInterval: "12h" # Refresh interval (optional, default: "12h")
ffmpeg: false # Use FFMPEG for remuxing (optional, default: true)
maxStreams: 3 # Maximum number of concurrent streams (optional, default: 1)
```

Avec 
```
cat /etc/debian_version
12.8
```

I think the probleme could be from the referer who can be blocked, so i try to change in provider.go : 
```
func loadReader(uri string) io.ReadCloser {
    var err error
    var reader io.ReadCloser
    logger := log.WithField("uri", uri)

    // Le Referer en dur
    referer := "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

    if isURL(uri) {
        // Créer une requête HTTP avec un en-tête Referer en dur
        req, err := http.NewRequest("GET", uri, nil)
        if err != nil {
            logger.WithError(err).Panic("unable to create request")
        }

        // Ajouter l'en-tête Referer
        req.Header.Add("Referer", referer)

        // Créer un client HTTP pour envoyer la requête
        client := &http.Client{}
        resp, err := client.Do(req)
        if err != nil {
            logger.WithError(err).Panic("unable to load uri")
        }
        defer resp.Body.Close() // Toujours fermer le body après utilisation

        if resp.StatusCode != http.StatusOK {
            logger.WithField("status", resp.StatusCode).Panic("invalid url response code")
        }

        reader = resp.Body
    } else {
        reader, err = os.Open(uri)
        if err != nil {
            logger.WithError(err).Panic("error loading file")
        }
    }

    return reader
}
```

But without success.

Could you help me please ?

Thanks

**Comment by csfrancis** [comment]
Sorry - I doubt there is much I can help you with here.

Are you able to load the URL in a web browser? Does it work if you use curl on the command line? 

If either of those work, I would suggest taking a look at what request headers they are sending.

**Comment by GitHub666k** [comment]
Hi thanks for you answer.

Yes i can download via web browser or via curl ( with a useragent different from curl)

If i do a tcpdump i can see : 

```
GET /get.php?username=*******&password=******&output=ts&type=m3u_plus HTTP/1.1
Host: myurl.onl
User-Agent: Go-http-client/1.1
Referer: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Accept-Encoding: gzip

HTTP/1.1 461
Server: CDN PROXY SERVICE
Date: Sat, 16 Nov 2024 21:22:21 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
```

So i understand my problem, I made a mistake, i change Referer instead of User-Agent

So i change the code

```
func loadReader(uri string) io.ReadCloser {
    var err error
    var reader io.ReadCloser
    logger := log.WithField("uri", uri)

    // Le User-Agent en dur
    userAgent := "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

    if isURL(uri) {
        // Créer une requête HTTP avec un User-Agent personnalisé
        req, err := http.NewRequest("GET", uri, nil)
        if err != nil {
            logger.WithError(err).Panic("unable to create request")
        }

        // Ajouter l'en-tête User-Agent
        req.Header.Add("User-Agent", userAgent)

        // Créer un client HTTP pour envoyer la requête
        client := &http.Client{}
        resp, err := client.Do(req)
        if err != nil {
            logger.WithError(err).Panic("unable to load uri")
        }
        defer resp.Body.Close() // Toujours fermer le body après utilisation

        if resp.StatusCode != http.StatusOK {
            logger.WithField("status", resp.StatusCode).Panic("invalid url response code")
        }

        reader = resp.Body
    } else {
        reader, err = os.Open(uri)
        if err != nil {
            logger.WithError(err).Panic("error loading file")
        }
    }
```

    return reader
}

And do again : 

```
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin
make setup
make build
```

And now it is ok : 

```
GET /get.php?username=******&password=******&output=ts&type=m3u_plus HTTP/1.1
Host: myurl.onl
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Accept-Encoding: gzip
HTTP/1.1 200 OK
Server: CDN PROXY SERVICE
Date: Sat, 16 Nov 2024 21:29:42 GMT
Content-Type: application/octet-stream
Content-Length: 28714198
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Description: File Transfer
Expires: 0
Cache-Control: must-revalidate
Pragma: public
Content-Disposition: attachment; filename="tv_channels_4W8ydt4448_plus.m3u"
Pragma: public
Cache-Control: public, must-revalidate, proxy-revalidate

#EXTM3U
#EXTINF:-1 tvg-id="" tvg-name="Skincare (FR) HD 2024" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ikPzv7el0RcBhtXj3ElCoH54icd.jpg" group-title="FILMS RÉCEMMENT AJOUTÉS",Skincare (FR) HD 2024
```

But now i have a new problem : 

```
INFO[2024-11-16T21:13:56Z] starting proxytv                              config=TV.yaml gitCommit=8e7aad7
INFO[2024-11-16T21:13:56Z] loading IPTV m3u                              url="http://myurl.onl/get.php?username=REDACTED&password=REDACTED&output=ts&type=m3u_plus"
DEBU[2024-11-16T21:14:00Z] loaded IPTV m3u                               duration=4.002708075s
FATA[2024-11-16T21:14:00Z] failed to load provider: http: read on closed response body
```
And I have in tcpdump this data : 

`
....
#EXTINF:-1 tvg-id="France24.fr" tvg-name="|FR| FRANCE 24 SD" tvg-logo="http://i.imgur.com/jELYlh5.png" group-title="FR TV SD (FRANCE)",|FR| FRANCE 24 SD`

Could you help me on this new problem and can you add the useragent in the config files

Thanks

**Comment by csfrancis** [comment]
I added custom user-agent support in 28d537d85421914ba2e2629e0ac24af57452cfc6. You can set it in the config.yaml with the `userAgent:` parameter:
```yaml
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
```

The problem you ran into with your code is that you are closing the stream when `loadReader` returns:
```go
        // Créer un client HTTP pour envoyer la requête
        client := &http.Client{}
        resp, err := client.Do(req)
        if err != nil {
            logger.WithError(err).Panic("unable to load uri")
        }
HERE -> defer resp.Body.Close() // Toujours fermer le body après utilisation
```

The reader is meant to be closed by the caller of `loadReader`, e.g.: https://github.com/csfrancis/proxytv/blob/eea07f3e1244b28ae67452e2bf3af4c75d716400/provider.go#L281-L282

**Comment by GitHub666k** [comment]
It works perfectly. Thank you for your hard work!
